import Head from 'next/head';
import { Inter } from 'next/font/google';
import RegisterForm from '@/components/Auth/RegisterForm';
import { Button } from 'flowbite-react';
import { useAuth } from '@/context/AuthContext';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';

const inter = Inter({ subsets: ['latin'] });

export default function Admin() {
  const [isLogOut, setIsLogout] = useState(false);

  const router = useRouter();

  const { logOut } = useAuth();

  const logOutUser = () => {
    logOut();
    setIsLogout(true);
  };

  const redirectToRegistration = () => {
    router.push('/admin/register');
  };

  useEffect(() => {
    if (isLogOut) router.push('/auth/login');
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center items-center min-h-screen w-full gap-10 flex-col from-gray-500 to-gray-300 bg-gradient-to-r">
        <section className="flex justify-center items-center gap-3 sm:flex-row">
          <p className="text-2xl font-bold">COMING SOON</p>
          <Button color="dark" onClick={logOutUser}>
            Logout
          </Button>
        </section>
        <section className="flex flex-col justify-center items-center gap-3">
          <p className="text-base leading-relaxed text-gray-800 dark:text-gray-400">
            You can still register accounts for employees
          </p>
          <Button
            color="light"
            className="w-full"
            onClick={redirectToRegistration}
          >
            Click here
          </Button>
        </section>
      </main>
    </>
  );
}
